version: "3.9"

services:
  quebrapaywall:
    build:
      context: .
    init: true
    image: quebrapaywall
    container_name: quebrapaywall
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    env_file: .env
    restart: unless-stopped
